export const homeObjOne = {
    lightBg: true,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightText: false,
    lightTextDesc: false, 
    topLine: '',
    headline: 'ON THIS DAY WE MAKE SURE TO KEEP TRACK OF ALL THE THINGS WE HAVE DONE, AND ALL THAT WE HAVE LEFT TO DO.',
    buttonLabel: '',
    description: 'In the last year we where able to see an incredible drop on pollution when everybody was urged to quarantine themselves. We where able to see the skies clear up, in a matter of days.',
    featuredImg: 'https://www.newmoonblog.com/wp-content/uploads/2020/02/Why-should-we-take-care-of-our-environment-1.jpg',
    featuredTitle: '',
    featuredDescription: '',
    featuredLink: '/',
    start: '',
    topspacing: false,
    shortDesc: true,
    backColor: '#b7cef1',
    accentColor: '#0061e1',
};

export const homeObjTwo = {
    lightBg: false,
    primary: true,
    imgStart: true,
    lightTopLine: true,
    lightText: false,
    lightTextDesc: false, 
    topLine: '',
    headline: '"The climate is changing why cant we?"',
    buttonLabel: '',
    description: 'Hundreds marched in the name of climate change. Filling the streets with signs for a better world.', 
    featuredImg: 'https://i.guim.co.uk/img/media/9d5cafc7d6781f37b15f92e54e6fa93af1802e5c/0_116_4203_2522/master/4203.jpg?width=1920&quality=85&auto=format&fit=max&s=2afa62dae4ae3499d5ce39b90f06b0f4',
    featuredTitle: '',
    featuredDescription: '',
    featuredLink: '/',
    topspacing: false,
    backColor: '#c4e5cc',
    accentColor: '#22cf57',
};

export const homeObjThree = {
    lightBg: true,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightText: false,
    lightTextDesc: false, 
    topLine: '.',
    headline: 'The breathgiving images of the air quality change in India.',
    buttonLabel: '',
    description: 'A series of images reveals the difference of air quality between a hyper active city versus a quarantined city.', 
    featuredImg: 'https://dynaimage.cdn.cnn.com/cnn/c_fill,g_auto,w_1200,h_675,ar_16:9/https%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F200401105309-20200401-indian-gate-air-pollution-split.jpg',
    featuredTitle: '',
    featuredDescription: '',
    featuredLink: '/',
    topspacing: false,
    backColor: '#d7a9dc',
    accentColor: '#c900e1',
};

export const gridObject = {
    gridImage: require('../../assets/categ-home.png').default,
};